{{- if ne .Values.identity false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  annotations:
    azure.workload.identity/client-id:  {{ .Values.azure.clientId }}
    azure.workload.identity/tenant-id:  {{ .Values.azure.tenantId }}
  labels:
    azure.workload.identity/use: "true"
{{- end }}